#include "tokens.h"
cparse_keyword_meta_t const cparse_keyword_tbl[59] = {
    (cparse_keyword_meta_t){CTOKEN_KW_ALIGNAS       ,"alignas"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW_ALIGNOF       ,"alignof"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW_AUTO          ,"auto"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_BOOL          ,"bool"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_BREAK         ,"break"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_CASE          ,"case"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_CHAR          ,"char"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_CONST         ,"const"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_CONSTEXPR     ,"constexpr"     ,9 },
    (cparse_keyword_meta_t){CTOKEN_KW_CONTINUE      ,"continue"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW_DEFAULT       ,"default"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW_DO            ,"do"            ,2 },
    (cparse_keyword_meta_t){CTOKEN_KW_DOUBLE        ,"double"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_ELSE          ,"else"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_ENUM          ,"enum"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_EXTERN        ,"extern"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_FALSE         ,"false"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_FLOAT         ,"float"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_FOR           ,"for"           ,3 },
    (cparse_keyword_meta_t){CTOKEN_KW_GOTO          ,"goto"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_IF            ,"if"            ,2 },
    (cparse_keyword_meta_t){CTOKEN_KW_INLINE        ,"inline"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_INT           ,"int"           ,3 },
    (cparse_keyword_meta_t){CTOKEN_KW_LONG          ,"long"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_NULLPTR       ,"nullptr"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW_REGISTER      ,"register"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW_RESTRICT      ,"restrict"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW_RETURN        ,"return"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_SHORT         ,"short"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_SIGNED        ,"signed"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_SIZEOF        ,"sizeof"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_STATIC        ,"static"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_STATIC_ASSERT ,"static_assert" ,13},
    (cparse_keyword_meta_t){CTOKEN_KW_STRUCT        ,"struct"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_SWITCH        ,"switch"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_THREAD_LOCAL  ,"thread_local"  ,12},
    (cparse_keyword_meta_t){CTOKEN_KW_TRUE          ,"true"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_TYPEDEF       ,"typedef"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW_TYPEOF        ,"typeof"        ,6 },
    (cparse_keyword_meta_t){CTOKEN_KW_TYPEOF_UNQUAL ,"typeof_unqual" ,13},
    (cparse_keyword_meta_t){CTOKEN_KW_UNION         ,"union"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW_UNSIGNED      ,"unsigned"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW_VOID          ,"void"          ,4 },
    (cparse_keyword_meta_t){CTOKEN_KW_VOLATILE      ,"volatile"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW_WHILE         ,"while"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW__ALIGNAS      ,"_Alignas"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW__ALIGNOF      ,"_Alignof"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW__ATOMIC       ,"_Atomic"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW__BITINT       ,"_BitInt"       ,7 },
    (cparse_keyword_meta_t){CTOKEN_KW__BOOL         ,"_Bool"         ,5 },
    (cparse_keyword_meta_t){CTOKEN_KW__COMPLEX      ,"_Complex"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW__DECIMAL128   ,"_Decimal128"   ,11},
    (cparse_keyword_meta_t){CTOKEN_KW__DECIMAL32    ,"_Decimal32"    ,10},
    (cparse_keyword_meta_t){CTOKEN_KW__DECIMAL64    ,"_Decimal64"    ,10},
    (cparse_keyword_meta_t){CTOKEN_KW__GENERIC      ,"_Generic"      ,8 },
    (cparse_keyword_meta_t){CTOKEN_KW__IMAGINARY    ,"_Imaginary"    ,10},
    (cparse_keyword_meta_t){CTOKEN_KW__NORETURN     ,"_Noreturn"     ,9 },
    (cparse_keyword_meta_t){CTOKEN_KW__STATIC_ASSERT,"_Static_assert",14},
    (cparse_keyword_meta_t){CTOKEN_KW__THREAD_LOCAL ,"_Thread_local" ,13},
};
